### ISSUE TITLE
PHP parsing problem

### ISSUE THREAD

**Issue by tazziedave** [logological/gpp#13] opened 2016-11-15 02:09 UTC
I'd like to use gpp to parse php to get different build versions. If I use the default option, the output is stripped of lonely '\\' characters. A problem when specifying '\r\n' => 'rn' but more importantly it removes the namespace separators. A real issue when trying to specify the root namespace:  \call() => call() which becomes a current namespace call. Infinite recursion here I come!

As far as I can tell none of the standard formats work completely (-C is closest but it strips all comments!).
Any suggestions? Thanks

Dave

**Comment by logological** [comment] 2020-07-23 19:38
@tazziedave: Sorry for the delayed response.  I think you may have overlooked that by default, GPP uses `\` as the quote character.  That is, this is a duplicate of Issue #15 and Issue #46, which you should consult for the solution.  (If I'm wrong, feel free to reopen this issue and provide further details.)

**Closed by logological** 2020-07-23 19:38 UTC
Labels: duplicate
